language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"

before_install:
  - curl http://ftp.gnu.org/gnu/lightning/lightning-2.1.0.tar.gz > /tmp/lightning-2.1.0.tar.gz
  - tar xfv /tmp/lightning-2.1.0.tar.gz
  - cd lightning-2.1.0
  - mkdir $HOME/usr
  - ./configure --prefix=$HOME/usr --enable-shared --disable-static --disable-disassembler
  - make -j
  - make -j install
  - cd ..

install:
  - python setup.py -q install

script:
  - LD_LIBRARY_PATH=$HOME/usr/lib:$LD_LIBRARY_PATH LD_PRELOAD=$HOME/usr/lib/liblightning.so python setup.py test

sudo: false
