language: python

python:
  - "2.7"

before_install:
  - curl http://ftp.gnu.org/gnu/lightning/lightning-2.1.0.tar.gz > /tmp/lightning-2.1.0.tar.gz
  - tar xfv /tmp/lightning-2.1.0.tar.gz
  - cd lightning-2.1.0
  - ./configure --enable-shared --disable-static --disable-disassembler --prefix=/tmp/lightning
  - make -j install
  - cd ..

install:
  - python setup.py -q install

script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/tmp/lightning/lib
  - python setup.py test
