language: python

python:
  - "2.7"

before_install:
  - curl http://ftp.gnu.org/gnu/lightning/lightning-2.1.0.tar.gz > /tmp/lightning-2.1.0.tar.gz
  - tar xfv /tmp/lightning-2.1.0.tar.gz
  - cd lightning-2.1.0
  - ./configure --prefix=/tmp/usr --enable-shared --disable-static --disable-disassembler
  - make -j install
  - cd ..
  - export LD_LIBRARY_PATH=/tmp/usr/lib:$LD_LIBRARY_PATH

install:
  - python setup.py -q install

script:
  - python setup.py test

sudo: false
