language: python

python:
  - "2.7"

before_install:
  - curl http://ftp.gnu.org/gnu/lightning/lightning-2.1.0.tar.gz > /tmp/lightning-2.1.0.tar.gz
  - tar xfv /tmp/lightning-2.1.0.tar.gz
  - cd lightning-2.1.0
  - ./configure --enable-shared --disable-static --disable-disassembler
  - make -j
  - sudo make -j install
  - cd ..

install:
  - python setup.py -q install

script:
  - python setup.py test

sudo: required
