language: python

python:
  - "2.7"

before_install:
  - curl http://ftp.gnu.org/gnu/lightning/lightning-2.1.0.tar.gz > /tmp/lightning-2.1.0.tar.gz
  - tar xfv /tmp/lightning-2.1.0.tar.gz
  - cd lightning-2.1.0
  - mkdir /opt-local
  - ./configure --prefix=/opt-local --enable-shared --disable-static --disable-disassembler
  - make -j
  - make -j install
  - cd ..
  - find /opt-local

install:
  - export LD_LIBRARY_PATH=/opt-local/lib:$LD_LIBRARY_PATH
  - python setup.py -q install

script:
  - python setup.py test

sudo: false
